const EVENT_CAPTURE_PAGE_SUMMARY = "CAPTURE_PAGE_SUMMARY";
const EVENT_FULL_PAGE_HTML_CONTENT = "FULL_PAGE_HTML_CONTENT";
const EVENT_FULL_PAGE_TEXT = "PAGE_TEXT";

export const EVENTS = {
    EVENT_CAPTURE_PAGE_SUMMARY,
    EVENT_FULL_PAGE_HTML_CONTENT,
    EVENT_FULL_PAGE_TEXT
} as const;